/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpos.view2;

import dao.CategoryDao;
import dao.ProjectDao;
import dao.PurchaseDao;
import dao.SupplierDao;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import projectpos.pos.PosUtil;

/**
 *
 * @author MY COMPUTER
 */
public class ProjectView extends javax.swing.JFrame {

    PosUtil pu=new PosUtil();
    ProjectDao pd=new ProjectDao();
    CategoryDao categoryDao=new CategoryDao();
    PurchaseDao purchaseDao=new PurchaseDao();
    SupplierDao supplierDao=new SupplierDao();
    
    
    
    
    /**
     * Creates new form ProjectView
     */
    public ProjectView() {
        initComponents();  
       pd.showAllCustomer(tableCustomers);
       categoryDao.showAllCategory(tableCategory);
       purchaseDao.loadCategory(comboPurchaseCategory);
       supplierDao.showAllSupplier(tableSuppliers);
       
       purchaseDao.loadCategory(comboPurchaseCategory);
       
       
       
       comboPurchaseCategory.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                String categoryName=comboPurchaseCategory.getSelectedItem().toString();
                
                purchaseDao.loadProduct(ComboBoxPurchaseProductName, categoryName);
               
            }
       });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabCustomer = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCustomerCell = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        btnCustomerSearchByAddress = new javax.swing.JButton();
        btnCustomerSave = new javax.swing.JButton();
        btnCustomerDelete = new javax.swing.JButton();
        btnCustomerReset = new javax.swing.JButton();
        btnCustomerEdit = new javax.swing.JButton();
        txtCustomerSearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomers = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        tabProduct = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtProductCustomerID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtProductExpiredDate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtProductUnitPrice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtProductQuantity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtProductTotalPrice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        txtProductCustomerName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        btnProductEdit = new javax.swing.JButton();
        btnProductSave = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabCategory = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCategoryName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCategoryID = new javax.swing.JTextField();
        btnCategoryDelete = new javax.swing.JButton();
        btnCategorySave = new javax.swing.JButton();
        btnCategoryEdit = new javax.swing.JButton();
        btnCategoryReset = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCategory = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tabSuppliers = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtSupplierContactPerson = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtSupplierId = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtSupplierCell = new javax.swing.JTextField();
        txtSupplierEmail = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtSupplierAddress = new javax.swing.JTextField();
        btnSupplierDelete = new javax.swing.JButton();
        btnSupplierSave = new javax.swing.JButton();
        btnSupplierEdit = new javax.swing.JButton();
        btnSupplierReset = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSuppliers = new javax.swing.JTable();
        btnSupplierRefresh = new javax.swing.JButton();
        tabPurchase = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ComboBoxPurchaseSupplierName = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        comboPurchaseCategory = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        ComboBoxPurchaseProductName = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        txtPurchaseTotalPrice = new javax.swing.JTextField();
        txtPurchaseUnitePrice = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtPurchaseQuantity = new javax.swing.JTextField();
        btnPurchaseReset = new javax.swing.JButton();
        btnPurchaseConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Project POS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCustomer.setText("Customer");
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerMouseClicked(evt);
            }
        });
        jPanel2.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 140, 30));

        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 30));

        btnSales.setText("Sales");
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesMouseClicked(evt);
            }
        });
        jPanel2.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        btnProduct.setText("Product");
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductMouseClicked(evt);
            }
        });
        jPanel2.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 30));

        btnStock.setText("Stock");
        btnStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStockMouseClicked(evt);
            }
        });
        jPanel2.add(btnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 140, 30));

        btnCategory.setText("Category");
        btnCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoryMouseClicked(evt);
            }
        });
        jPanel2.add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 30));

        btnPurchase.setText("Purchase");
        btnPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPurchaseMouseClicked(evt);
            }
        });
        jPanel2.add(btnPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 140, 30));

        btnSuppliers.setText("Suppliers");
        btnSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuppliersMouseClicked(evt);
            }
        });
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 140, 740));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        tabCustomer.setEnabled(false);

        jLabel2.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel2)
                .addContainerGap(556, Short.MAX_VALUE))
        );

        tabCustomer.addTab("tab1", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, 53, -1));
        jPanel4.add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 39, 161, -1));

        jLabel10.setText("Name");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 53, -1));

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 79, 161, -1));

        jLabel11.setText("Cell");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 42, 53, -1));
        jPanel4.add(txtCustomerCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 39, 161, -1));

        jLabel12.setText("Email");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 82, 53, -1));
        jPanel4.add(txtCustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 79, 161, -1));

        jLabel13.setText("Address");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 59, -1));
        jPanel4.add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 113, 430, -1));

        btnCustomerSearchByAddress.setBackground(new java.awt.Color(204, 204, 255));
        btnCustomerSearchByAddress.setText("Search By Address");
        btnCustomerSearchByAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerSearchByAddressMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerSearchByAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        btnCustomerSave.setBackground(new java.awt.Color(204, 255, 204));
        btnCustomerSave.setText("Save");
        btnCustomerSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        btnCustomerDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnCustomerDelete.setText("Delete");
        btnCustomerDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerDeleteMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        btnCustomerReset.setBackground(new java.awt.Color(255, 255, 204));
        btnCustomerReset.setText("Reset");
        btnCustomerReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerResetMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        btnCustomerEdit.setBackground(new java.awt.Color(153, 153, 153));
        btnCustomerEdit.setText("Edit");
        btnCustomerEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerEditMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        txtCustomerSearchField.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.add(txtCustomerSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 190, -1));

        tableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCustomers);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 960, 490));

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Customers Details ");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 960, 60));

        btnRefresh.setBackground(new java.awt.Color(255, 153, 51));
        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        jPanel4.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        tabCustomer.addTab("tab2", jPanel4);

        tabProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("ID");
        tabProduct.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 39, 57, 25));
        tabProduct.add(txtProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 107, -1));

        jLabel15.setText("Name");
        tabProduct.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 60, 20));
        tabProduct.add(txtProductCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, -1));

        jLabel19.setText("Expired Date");
        tabProduct.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 20));
        tabProduct.add(txtProductExpiredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, -1));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Unit Price");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 20));
        jPanel5.add(txtProductUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, -1));

        jLabel17.setText("Quantity");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 20));

        txtProductQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProductQuantityFocusLost(evt);
            }
        });
        jPanel5.add(txtProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 255));
        jLabel18.setText("Total Price");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, 20));

        txtProductTotalPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProductTotalPriceMouseClicked(evt);
            }
        });
        jPanel5.add(txtProductTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 150, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Price Section");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, 30));

        tabProduct.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 450, 160));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Product Details ");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        tabProduct.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 960, 70));

        tableProduct.setBackground(new java.awt.Color(204, 204, 255));
        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableProduct);

        tabProduct.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 960, 490));

        jLabel22.setText("Customer ID by Search");
        tabProduct.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 60));
        tabProduct.add(txtProductCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 150, -1));

        jLabel23.setText("Customer Name");
        tabProduct.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 100, 20));
        tabProduct.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 150, -1));

        btnProductEdit.setText("Edit");
        tabProduct.add(btnProductEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        btnProductSave.setText("Save");
        tabProduct.add(btnProductSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jButton10.setText("Reset");
        tabProduct.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jButton11.setText("Delete");
        tabProduct.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        tabCustomer.addTab("tab3", tabProduct);

        jLabel5.setText("4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(473, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel5)
                .addContainerGap(620, Short.MAX_VALUE))
        );

        tabCustomer.addTab("tab4", jPanel6);

        tabCategory.setEnabled(false);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 960, -1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        jLabel6.setText("Name");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 60, -1));
        jPanel9.add(txtCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 170, -1));

        jLabel24.setText("ID");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, -1));
        jPanel9.add(txtCategoryID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, -1));

        btnCategoryDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnCategoryDelete.setText("Delete");
        btnCategoryDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoryDeleteMouseClicked(evt);
            }
        });
        jPanel9.add(btnCategoryDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        btnCategorySave.setBackground(new java.awt.Color(153, 153, 255));
        btnCategorySave.setText("Save");
        btnCategorySave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategorySaveMouseClicked(evt);
            }
        });
        jPanel9.add(btnCategorySave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btnCategoryEdit.setBackground(new java.awt.Color(0, 255, 51));
        btnCategoryEdit.setText("Edit");
        btnCategoryEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoryEditMouseClicked(evt);
            }
        });
        jPanel9.add(btnCategoryEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        btnCategoryReset.setBackground(new java.awt.Color(0, 255, 204));
        btnCategoryReset.setText("Reset");
        btnCategoryReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoryResetMouseClicked(evt);
            }
        });
        jPanel9.add(btnCategoryReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jPanel12.setBackground(new java.awt.Color(153, 102, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Category");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        tableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoryMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableCategory);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 287, 960, 450));

        jPanel20.setBackground(new java.awt.Color(51, 51, 255));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Categories Table");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 960, 60));

        tabCategory.addTab("tab1", jPanel9);

        tabCustomer.addTab("tab5", tabCategory);

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(255, 51, 51));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Stock");
        jPanel23.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jTabbedPane3.addTab("tab1", jPanel22);

        tabCustomer.addTab("tab6", jTabbedPane3);

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(0, 153, 153));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Suppliers");
        jPanel19.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jLabel33.setText("ID");
        jPanel18.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));
        jPanel18.add(txtSupplierContactPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 230, -1));

        jLabel34.setText("Email");
        jPanel18.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 60, 20));
        jPanel18.add(txtSupplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 160, -1));

        jLabel35.setText("Contact Person");
        jPanel18.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 90, 20));
        jPanel18.add(txtSupplierCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 160, -1));
        jPanel18.add(txtSupplierEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 190, -1));

        jLabel36.setText("Cell");
        jPanel18.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 20));

        jLabel37.setText("Name");
        jPanel18.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 60, 20));
        jPanel18.add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 190, -1));

        jLabel38.setText("Address");
        jPanel18.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 70, 20));
        jPanel18.add(txtSupplierAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 230, -1));

        btnSupplierDelete.setText("Delete");
        btnSupplierDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierDeleteMouseClicked(evt);
            }
        });
        jPanel18.add(btnSupplierDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        btnSupplierSave.setText("Save");
        btnSupplierSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierSaveMouseClicked(evt);
            }
        });
        jPanel18.add(btnSupplierSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        btnSupplierEdit.setText("Edit");
        btnSupplierEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierEditMouseClicked(evt);
            }
        });
        jPanel18.add(btnSupplierEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        btnSupplierReset.setText("Reset");
        btnSupplierReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierResetMouseClicked(evt);
            }
        });
        jPanel18.add(btnSupplierReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jPanel21.setBackground(new java.awt.Color(0, 102, 51));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Suppliers Info Table");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 960, 60));

        tableSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSuppliersMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableSuppliers);

        jPanel18.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 960, 440));

        btnSupplierRefresh.setText("Refresh");
        btnSupplierRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierRefreshMouseClicked(evt);
            }
        });
        jPanel18.add(btnSupplierRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        tabSuppliers.addTab("tab1", jPanel18);

        tabCustomer.addTab("tab7", tabSuppliers);

        tabPurchase.setBackground(new java.awt.Color(102, 255, 204));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 954, -1));

        jLabel9.setText("Supplier Name");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 90, -1));

        ComboBoxPurchaseSupplierName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel13.add(ComboBoxPurchaseSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 140, -1));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 954, -1));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        comboPurchaseCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel13.add(comboPurchaseCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, -1));

        jLabel26.setText("Category");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 20));

        jPanel17.setBackground(new java.awt.Color(0, 153, 153));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Purchase");
        jPanel17.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jPanel13.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jLabel28.setText("Product Name");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 90, -1));

        ComboBoxPurchaseProductName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel13.add(ComboBoxPurchaseProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 140, -1));

        jLabel29.setText("Total Price");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 70, -1));
        jPanel13.add(txtPurchaseTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 140, -1));
        jPanel13.add(txtPurchaseUnitePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));

        jLabel30.setText("Quantity");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 60, -1));

        jLabel31.setText("Unite Price");
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));
        jPanel13.add(txtPurchaseQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 140, -1));

        btnPurchaseReset.setBackground(new java.awt.Color(0, 255, 102));
        btnPurchaseReset.setText("Reset");
        jPanel13.add(btnPurchaseReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        btnPurchaseConfirm.setBackground(new java.awt.Color(153, 153, 255));
        btnPurchaseConfirm.setText("Confirm");
        jPanel13.add(btnPurchaseConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        tabPurchase.addTab("tab1", jPanel13);

        tabCustomer.addTab("tab8", tabPurchase);

        getContentPane().add(tabCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 960, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void resetCustomer(){
    
        txtCustomerId.setText("");
        txtCustomerName.setText("");
        txtCustomerCell.setText("");
        txtCustomerEmail.setText("");
        txtCustomerAddress.setText("");
    
    }
    
    public void resetCategory(){
    
        txtCategoryID.setText("");
        txtCategoryName.setText("");
    
    }
    
    public void resetSupplier(){
    
        txtSupplierId.setText("");
        txtSupplierName.setText("");
        txtSupplierCell.setText("");
        txtSupplierEmail.setText("");
        txtSupplierAddress.setText("");
        txtSupplierContactPerson.setText("");
    
    
    }
    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(0);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(1);
    }//GEN-LAST:event_btnCustomerMouseClicked

    private void btnProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(2);
    }//GEN-LAST:event_btnProductMouseClicked

    private void btnSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(3);
    }//GEN-LAST:event_btnSalesMouseClicked

    private void btnCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoryMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(4);
        
    }//GEN-LAST:event_btnCategoryMouseClicked

    private void btnStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(5);
    }//GEN-LAST:event_btnStockMouseClicked

    private void btnSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuppliersMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(6);
    }//GEN-LAST:event_btnSuppliersMouseClicked

    private void btnPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPurchaseMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(7);
      //  purchaseDao.loadCategory(comboPurchaseCategory);
    }//GEN-LAST:event_btnPurchaseMouseClicked

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnCustomerSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseClicked
        // TODO add your handling code here:
       String name=txtCustomerName.getText().trim();
       String cell=txtCustomerCell.getText().trim();
       String email=txtCustomerEmail.getText().trim();
       String address=txtCustomerAddress.getText().trim();
        
        pd.saveCustomer(name, cell, email, address);
        resetCustomer();
        
    }//GEN-LAST:event_btnCustomerSaveMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        pd.showAllCustomer(tableCustomers);
        resetCustomer();
        btnCustomerSave.setVisible(true);
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnCustomerResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerResetMouseClicked
        // TODO add your handling code here:
        
        resetCustomer();
        btnCustomerSave.setVisible(true);
        
    }//GEN-LAST:event_btnCustomerResetMouseClicked

    private void tableCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomersMouseClicked
        // TODO add your handling code here:
        btnCustomerSave.setVisible(false);
        int rowIndex=tableCustomers.getSelectedRow();
        
        String id=tableCustomers.getModel().getValueAt(rowIndex, 0).toString();
        String name=tableCustomers.getModel().getValueAt(rowIndex, 1).toString();
        String cell=tableCustomers.getModel().getValueAt(rowIndex, 2).toString();
        String email=tableCustomers.getModel().getValueAt(rowIndex, 3).toString();
        String address=tableCustomers.getModel().getValueAt(rowIndex, 4).toString();
        
        txtCustomerId.setText(id);
        txtCustomerName.setText(name);
        txtCustomerCell.setText(cell);
        txtCustomerEmail.setText(email);
        txtCustomerAddress.setText(address);
        
        
        
        
    }//GEN-LAST:event_tableCustomersMouseClicked

    private void btnCustomerDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerDeleteMouseClicked
        // TODO add your handling code here:
        int id=Integer.parseInt(txtCustomerId.getText());
        pd.deleteCustomer(id, tableCustomers);
        resetCustomer();
        btnCustomerSave.setVisible(true);
    }//GEN-LAST:event_btnCustomerDeleteMouseClicked

    private void btnCustomerEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerEditMouseClicked
        // TODO add your handling code here:
        int id=Integer.parseInt(txtCustomerId.getText());
        String name=txtCustomerName.getText().trim();
        String cell=txtCustomerCell.getText().trim();
        String email=txtCustomerEmail.getText().trim();
        String address=txtCustomerAddress.getText().trim();
        
        pd.editCustomer(id, name, cell, email, address, tableCustomers);
        resetCustomer();
        btnCustomerSave.setVisible(true);
    }//GEN-LAST:event_btnCustomerEditMouseClicked

    private void btnCustomerSearchByAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSearchByAddressMouseClicked
        // TODO add your handling code here:
        String address=txtCustomerSearchField.getText().toLowerCase().trim();
        pd.searchCustomerByAddress(address, tableCustomers);
       
    }//GEN-LAST:event_btnCustomerSearchByAddressMouseClicked

    public void productTotalPrice(){
    
    double n1=Double.parseDouble(txtProductUnitPrice.getText().toString().trim());
    double n2=Double.parseDouble(txtProductQuantity.getText().toString().trim());
    double n=n1*n2;
    txtProductTotalPrice.setText(n+"");
    }
    
    
    
    
    private void txtProductTotalPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductTotalPriceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductTotalPriceMouseClicked

    private void txtProductQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProductQuantityFocusLost
        // TODO add your handling code here:
        productTotalPrice();
        
    }//GEN-LAST:event_txtProductQuantityFocusLost

    private void btnCategorySaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategorySaveMouseClicked
        // TODO add your handling code here:
        String name=txtCategoryName.getText().toString().trim();
        categoryDao.saveCategory(name);
        resetCategory();
        categoryDao.showAllCategory(tableCategory);
    }//GEN-LAST:event_btnCategorySaveMouseClicked

    private void btnCategoryResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoryResetMouseClicked
        // TODO add your handling code here:
        resetCategory();
        btnCategorySave.setVisible(true);
        
    }//GEN-LAST:event_btnCategoryResetMouseClicked

    private void tableCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoryMouseClicked
        // TODO add your handling code here:
        btnCategorySave.setVisible(false);
         int rowIndex=tableCategory.getSelectedRow();
         
       String id=tableCategory.getModel().getValueAt(rowIndex, 0).toString();
       String name=tableCategory.getModel().getValueAt(rowIndex, 1).toString();
       txtCategoryID.setText(id);
       txtCategoryName.setText(name);
       
    }//GEN-LAST:event_tableCategoryMouseClicked

    private void btnCategoryEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoryEditMouseClicked
        // TODO add your handling code here:
        
        int id=Integer.parseInt(txtCategoryID.getText());
        String name=txtCategoryName.getText().trim();
        categoryDao.editCategory(id, name, tableCategory);
        resetCategory();
        categoryDao.showAllCategory(tableCategory);
         btnCategorySave.setVisible(true);
         
    }//GEN-LAST:event_btnCategoryEditMouseClicked

    private void btnCategoryDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoryDeleteMouseClicked
        // TODO add your handling code here:
        int id=Integer.parseInt(txtCategoryID.getText());
        categoryDao.deleteCategory(id, tableCategory);
        resetCategory();
        categoryDao.showAllCategory(tableCategory);
         btnCategorySave.setVisible(true);
    }//GEN-LAST:event_btnCategoryDeleteMouseClicked

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnSupplierSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierSaveMouseClicked
        // TODO add your handling code here:
        String name=txtSupplierName.getText().trim();
        String cell=txtSupplierCell.getText().trim();
        String email=txtSupplierEmail.getText().trim();
        String address=txtSupplierAddress.getText().trim();
        String contactPerson=txtSupplierContactPerson.getText().trim();
        
        supplierDao.saveSupplier(name, cell, email, address, contactPerson);
        supplierDao.showAllSupplier(tableSuppliers);
        resetSupplier();
    }//GEN-LAST:event_btnSupplierSaveMouseClicked

    private void btnSupplierResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierResetMouseClicked
        // TODO add your handling code here:
        resetSupplier();
        btnSupplierSave.setVisible(true);
    }//GEN-LAST:event_btnSupplierResetMouseClicked

    private void btnSupplierRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierRefreshMouseClicked
        // TODO add your handling code here:
        supplierDao.showAllSupplier(tableSuppliers);
        resetSupplier();
        btnSupplierSave.setVisible(true);
    }//GEN-LAST:event_btnSupplierRefreshMouseClicked

    private void btnSupplierEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierEditMouseClicked
        // TODO add your handling code here:
        int id=Integer.parseInt(txtSupplierId.getText());
        String name=txtSupplierName.getText().trim();
        String cell=txtSupplierCell.getText().trim();
        String email=txtSupplierEmail.getText().trim();
        String address=txtSupplierAddress.getText().trim();
        String contactPerson=txtSupplierContactPerson.getText().trim();
        
        supplierDao.editSupplier(id, name, cell, email, address, contactPerson, tableProduct);
        supplierDao.showAllSupplier(tableSuppliers);
        btnSupplierSave.setVisible(true);
        
    }//GEN-LAST:event_btnSupplierEditMouseClicked

    private void btnSupplierDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierDeleteMouseClicked
        // TODO add your handling code here:
        int id=Integer.parseInt(txtSupplierId.getText());
        supplierDao.deleteSupplier(id, tableSuppliers);
        resetSupplier();
        supplierDao.showAllSupplier(tableSuppliers);
        btnSupplierSave.setVisible(true);
    }//GEN-LAST:event_btnSupplierDeleteMouseClicked

    private void tableSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSuppliersMouseClicked
        // TODO add your handling code here:
        btnSupplierSave.setVisible(false);
        int rowIndex=tableSuppliers.getSelectedRow();
        
        String id= tableSuppliers.getModel().getValueAt(rowIndex, 0).toString();
        String name= tableSuppliers.getModel().getValueAt(rowIndex, 1).toString();
        String cell= tableSuppliers.getModel().getValueAt(rowIndex, 2).toString();
        String email= tableSuppliers.getModel().getValueAt(rowIndex, 3).toString();
        String address= tableSuppliers.getModel().getValueAt(rowIndex, 4).toString();
        String contactPerson= tableSuppliers.getModel().getValueAt(rowIndex, 5).toString();
        
        
        txtSupplierId.setText(id);
        txtSupplierName.setText(name);
        txtSupplierCell.setText(cell);
        txtSupplierEmail.setText(email);
        txtSupplierAddress.setText(address);
        txtSupplierContactPerson.setText(contactPerson);
    }//GEN-LAST:event_tableSuppliersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPurchaseProductName;
    private javax.swing.JComboBox<String> ComboBoxPurchaseSupplierName;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnCategoryDelete;
    private javax.swing.JButton btnCategoryEdit;
    private javax.swing.JButton btnCategoryReset;
    private javax.swing.JButton btnCategorySave;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnCustomerDelete;
    private javax.swing.JButton btnCustomerEdit;
    private javax.swing.JButton btnCustomerReset;
    private javax.swing.JButton btnCustomerSave;
    private javax.swing.JButton btnCustomerSearchByAddress;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnProductEdit;
    private javax.swing.JButton btnProductSave;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnPurchaseConfirm;
    private javax.swing.JButton btnPurchaseReset;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnSupplierDelete;
    private javax.swing.JButton btnSupplierEdit;
    private javax.swing.JButton btnSupplierRefresh;
    private javax.swing.JButton btnSupplierReset;
    private javax.swing.JButton btnSupplierSave;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JComboBox<String> comboPurchaseCategory;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane tabCategory;
    private javax.swing.JTabbedPane tabCustomer;
    private javax.swing.JPanel tabProduct;
    private javax.swing.JTabbedPane tabPurchase;
    private javax.swing.JTabbedPane tabSuppliers;
    private javax.swing.JTable tableCategory;
    private javax.swing.JTable tableCustomers;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTable tableSuppliers;
    private javax.swing.JTextField txtCategoryID;
    private javax.swing.JTextField txtCategoryName;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerCell;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerSearchField;
    private javax.swing.JTextField txtProductCustomerID;
    private javax.swing.JTextField txtProductCustomerName;
    private javax.swing.JTextField txtProductExpiredDate;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductQuantity;
    private javax.swing.JTextField txtProductTotalPrice;
    private javax.swing.JTextField txtProductUnitPrice;
    private javax.swing.JTextField txtPurchaseQuantity;
    private javax.swing.JTextField txtPurchaseTotalPrice;
    private javax.swing.JTextField txtPurchaseUnitePrice;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierCell;
    private javax.swing.JTextField txtSupplierContactPerson;
    private javax.swing.JTextField txtSupplierEmail;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtSupplierName;
    // End of variables declaration//GEN-END:variables
}
