/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpos.view2;

import dao.ProjectDao;
import javax.swing.JOptionPane;
import projectpos.pos.PosUtil;

/**
 *
 * @author MY COMPUTER
 */
public class ProjectView extends javax.swing.JFrame {

    PosUtil pu=new PosUtil();
    ProjectDao pd=new ProjectDao();
    /**
     * Creates new form ProjectView
     */
    public ProjectView() {
        initComponents();  
       pd.showAllCustomer(tableCustomers);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabCustomer = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCustomerCell = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        btnCustomerSearchByAddress = new javax.swing.JButton();
        btnCustomerSave = new javax.swing.JButton();
        btnCustomerDelete = new javax.swing.JButton();
        btnCustomerReset = new javax.swing.JButton();
        btnCustomerEdit = new javax.swing.JButton();
        txtCustomerSearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomers = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        tabProduct = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtProductCustomerID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtProductExpiredDate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtProductUnitPrice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtProductQuantity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtProductTotalPrice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        txtProductCustomerName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        btnProductEdit = new javax.swing.JButton();
        btnProductSave = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Project POS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCustomer.setText("Customer");
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerMouseClicked(evt);
            }
        });
        jPanel2.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 140, 30));

        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 30));

        jButton3.setText("Sales");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        btnProduct.setText("Product");
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductMouseClicked(evt);
            }
        });
        jPanel2.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 30));

        jButton5.setText("Stock");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 140, 30));

        jButton6.setText("Category");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 30));

        jButton7.setText("History");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 140, 30));

        jButton8.setText("Suppliers");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 140, 740));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        tabCustomer.setEnabled(false);

        jLabel2.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel2)
                .addContainerGap(556, Short.MAX_VALUE))
        );

        tabCustomer.addTab("tab1", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, 53, -1));
        jPanel4.add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 39, 161, -1));

        jLabel10.setText("Name");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 53, -1));

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 79, 161, -1));

        jLabel11.setText("Cell");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 42, 53, -1));
        jPanel4.add(txtCustomerCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 39, 161, -1));

        jLabel12.setText("Email");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 82, 53, -1));
        jPanel4.add(txtCustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 79, 161, -1));

        jLabel13.setText("Address");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 59, -1));
        jPanel4.add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 113, 430, -1));

        btnCustomerSearchByAddress.setBackground(new java.awt.Color(204, 204, 255));
        btnCustomerSearchByAddress.setText("Search By Address");
        btnCustomerSearchByAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerSearchByAddressMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerSearchByAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        btnCustomerSave.setBackground(new java.awt.Color(204, 255, 204));
        btnCustomerSave.setText("Save");
        btnCustomerSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        btnCustomerDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnCustomerDelete.setText("Delete");
        btnCustomerDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerDeleteMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        btnCustomerReset.setBackground(new java.awt.Color(255, 255, 204));
        btnCustomerReset.setText("Reset");
        btnCustomerReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerResetMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        btnCustomerEdit.setBackground(new java.awt.Color(153, 153, 153));
        btnCustomerEdit.setText("Edit");
        btnCustomerEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerEditMouseClicked(evt);
            }
        });
        jPanel4.add(btnCustomerEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        txtCustomerSearchField.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.add(txtCustomerSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 190, -1));

        tableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCustomers);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 960, 490));

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Customers Details ");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 60));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 960, 60));

        btnRefresh.setBackground(new java.awt.Color(255, 153, 51));
        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        jPanel4.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        tabCustomer.addTab("tab2", jPanel4);

        tabProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("ID");
        tabProduct.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 39, 57, 25));
        tabProduct.add(txtProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 107, -1));

        jLabel15.setText("Name");
        tabProduct.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 60, 20));
        tabProduct.add(txtProductCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, -1));

        jLabel19.setText("Expired Date");
        tabProduct.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 20));
        tabProduct.add(txtProductExpiredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, -1));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Unit Price");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 20));
        jPanel5.add(txtProductUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, -1));

        jLabel17.setText("Quantity");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 20));

        txtProductQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProductQuantityFocusLost(evt);
            }
        });
        jPanel5.add(txtProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 255));
        jLabel18.setText("Total Price");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, 20));

        txtProductTotalPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProductTotalPriceMouseClicked(evt);
            }
        });
        jPanel5.add(txtProductTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 150, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Price Section");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, 30));

        tabProduct.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 450, 160));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Product Details ");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        tabProduct.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 960, 70));

        tableProduct.setBackground(new java.awt.Color(204, 204, 255));
        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableProduct);

        tabProduct.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 960, 490));

        jLabel22.setText("Customer ID by Search");
        tabProduct.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 60));
        tabProduct.add(txtProductCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 150, -1));

        jLabel23.setText("Customer Name");
        tabProduct.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 100, 20));
        tabProduct.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 150, -1));

        btnProductEdit.setText("Edit");
        tabProduct.add(btnProductEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        btnProductSave.setText("Save");
        tabProduct.add(btnProductSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jButton10.setText("Reset");
        tabProduct.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jButton11.setText("Delete");
        tabProduct.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        tabCustomer.addTab("tab3", tabProduct);

        jLabel5.setText("4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(473, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel5)
                .addContainerGap(620, Short.MAX_VALUE))
        );

        tabCustomer.addTab("tab4", jPanel6);

        jTabbedPane2.setEnabled(false);

        jLabel6.setText("5");
        jTabbedPane2.addTab("tab1", jLabel6);

        tabCustomer.addTab("tab5", jTabbedPane2);

        jLabel7.setText("6");
        jTabbedPane3.addTab("tab1", jLabel7);

        tabCustomer.addTab("tab6", jTabbedPane3);

        jLabel8.setText("7");
        jTabbedPane4.addTab("tab1", jLabel8);

        tabCustomer.addTab("tab7", jTabbedPane4);

        jLabel9.setText("8");
        jTabbedPane5.addTab("tab1", jLabel9);

        tabCustomer.addTab("tab8", jTabbedPane5);

        getContentPane().add(tabCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 960, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void resetCustomer(){
    
        txtCustomerId.setText("");
        txtCustomerName.setText("");
        txtCustomerCell.setText("");
        txtCustomerEmail.setText("");
        txtCustomerAddress.setText("");
    
    
    }
    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(0);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(1);
    }//GEN-LAST:event_btnCustomerMouseClicked

    private void btnProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(2);
    }//GEN-LAST:event_btnProductMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(3);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(4);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(5);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(6);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        tabCustomer.setSelectedIndex(7);
    }//GEN-LAST:event_jButton7MouseClicked

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnCustomerSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseClicked
        // TODO add your handling code here:
       String name=txtCustomerName.getText().trim();
       String cell=txtCustomerCell.getText().trim();
       String email=txtCustomerEmail.getText().trim();
       String address=txtCustomerAddress.getText().trim();
        
        pd.saveCustomer(name, cell, email, address);
        resetCustomer();
        
    }//GEN-LAST:event_btnCustomerSaveMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        pd.showAllCustomer(tableCustomers);
        resetCustomer();
        btnCustomerSave.setVisible(true);
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnCustomerResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerResetMouseClicked
        // TODO add your handling code here:
        
        resetCustomer();
        btnCustomerSave.setVisible(true);
        
    }//GEN-LAST:event_btnCustomerResetMouseClicked

    private void tableCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomersMouseClicked
        // TODO add your handling code here:
        btnCustomerSave.setVisible(false);
        int rowIndex=tableCustomers.getSelectedRow();
        
        String id=tableCustomers.getModel().getValueAt(rowIndex, 0).toString();
        String name=tableCustomers.getModel().getValueAt(rowIndex, 1).toString();
        String cell=tableCustomers.getModel().getValueAt(rowIndex, 2).toString();
        String email=tableCustomers.getModel().getValueAt(rowIndex, 3).toString();
        String address=tableCustomers.getModel().getValueAt(rowIndex, 4).toString();
        
        txtCustomerId.setText(id);
        txtCustomerName.setText(name);
        txtCustomerCell.setText(cell);
        txtCustomerEmail.setText(email);
        txtCustomerAddress.setText(address);
        
        
        
        
    }//GEN-LAST:event_tableCustomersMouseClicked

    private void btnCustomerDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerDeleteMouseClicked
        // TODO add your handling code here:
        int id=Integer.parseInt(txtCustomerId.getText());
        pd.deleteCustomer(id, tableCustomers);
        resetCustomer();
        btnCustomerSave.setVisible(true);
    }//GEN-LAST:event_btnCustomerDeleteMouseClicked

    private void btnCustomerEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerEditMouseClicked
        // TODO add your handling code here:
        int id=Integer.parseInt(txtCustomerId.getText());
        String name=txtCustomerName.getText().trim();
        String cell=txtCustomerCell.getText().trim();
        String email=txtCustomerEmail.getText().trim();
        String address=txtCustomerAddress.getText().trim();
        
        pd.editCustomer(id, name, cell, email, address, tableCustomers);
        resetCustomer();
        btnCustomerSave.setVisible(true);
    }//GEN-LAST:event_btnCustomerEditMouseClicked

    private void btnCustomerSearchByAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSearchByAddressMouseClicked
        // TODO add your handling code here:
        String address=txtCustomerSearchField.getText().toLowerCase().trim();
        pd.searchCustomerByAddress(address, tableCustomers);
       
    }//GEN-LAST:event_btnCustomerSearchByAddressMouseClicked

    public void productTotalPrice(){
    
    double n1=Double.parseDouble(txtProductUnitPrice.getText().toString().trim());
    double n2=Double.parseDouble(txtProductQuantity.getText().toString().trim());
    double n=n1*n2;
    txtProductTotalPrice.setText(n+"");
    }
    
    
    
    
    private void txtProductTotalPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductTotalPriceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductTotalPriceMouseClicked

    private void txtProductQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProductQuantityFocusLost
        // TODO add your handling code here:
        productTotalPrice();
        
    }//GEN-LAST:event_txtProductQuantityFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnCustomerDelete;
    private javax.swing.JButton btnCustomerEdit;
    private javax.swing.JButton btnCustomerReset;
    private javax.swing.JButton btnCustomerSave;
    private javax.swing.JButton btnCustomerSearchByAddress;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnProductEdit;
    private javax.swing.JButton btnProductSave;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane tabCustomer;
    private javax.swing.JPanel tabProduct;
    private javax.swing.JTable tableCustomers;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerCell;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerSearchField;
    private javax.swing.JTextField txtProductCustomerID;
    private javax.swing.JTextField txtProductCustomerName;
    private javax.swing.JTextField txtProductExpiredDate;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductQuantity;
    private javax.swing.JTextField txtProductTotalPrice;
    private javax.swing.JTextField txtProductUnitPrice;
    // End of variables declaration//GEN-END:variables
}
